/transactions:
  get:
    security:
      - Bearer: []
    tags:
      - Transactions
    summary: List all transactions
    description: Retrieve a list of all transactions, optionally filtered by month and user ID
    parameters:
      - in: query
        name: month
        description: The month to filter transactions (format: YYYY-MM)
        required: false
        type: string
        format: date
      - in: query
        name: userId
        description: The ID of the user to filter transactions
        required: false
        type: string
    produces:
      - application/json
    responses:
      '200':
        description: List of transactions retrieved successfully
        schema:
          type: array
          items:
            $ref: '#/definitions/Transaction'
      '400':
        description: Invalid parameters (e.g., month format or missing user ID)
      '401':
        description: Unauthorized
      '403':
        description: Forbidden
      '500':
        description: Internal Server Error