swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
- http
paths:
  /user/login:
    post:
      tags:
      - User Module
      summary: Login
      description: API for Login
      parameters:
      - in: body
        name: body
        description: Login Payload
        required: true
        schema:
          $ref: '#/definitions/Login'
      produces:
      - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions:
    get:
      security:
      - Bearer: []
      tags:
      - Transactions
      summary: List all transactions
      description: Retrieve a list of all transactions, optionally filtered by month and user ID
      parameters:
      - in: query
        name: month
        description: The month to filter transactions
        required: false
        type: string
        format: date
      - in: query
        name: userId
        description: The ID of the user to filter transactions
        required: false
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: List of transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid parameters (e.g., month format or missing user ID)
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

  /transactions/{id}:
    get:
      security:
      - Bearer: []
      tags:
      - Transactions
      summary: Get a specific transaction by ID
      description: Retrieve a single transaction using its ID
      parameters:
      - in: path
        name: id
        description: The ID of the transaction to retrieve
        required: true
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    put:
      security:
      - Bearer: []
      tags:
      - Transactions
      summary: Update transaction category and notes
      description: Update the category and notes of a specific transaction
      parameters:
      - in: path
        name: id
        description: The ID of the transaction to update
        required: true
        type: string
      - in: body
        name: body
        description: The updated transaction details
        required: true
        schema:
          $ref: '#/definitions/UpdateTransaction'
      produces:
      - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      date:
        type: string
        format: date-time
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Balance after the transaction
      type:
        type: string
        description: ID of the type from the predefined list
      category:
        type: string
        description: ID of the category from the predefined list
      notes:
        type: string
        description: Additional notes about the transaction

  UpdateTransaction:
    type: object
    properties:
      category:
        type: string
        description: Updated category ID of the transaction
      notes:
        type: string
        description: Updated notes about the transaction

  Login:
    type: object
    properties:
      username:
        type: string
        description: The username of the user
      password:
        type: string
        description: The password of the user

  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: The JWT token returned after successful login
